export const SUBMIT_CREATE_FORM = 'SUBMIT_CREATE_FORM'

export const EMPTY_CONTACT_LIST = 'EMPTY_CONTACT_LIST'
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const CREATE_SUCCESS = 'CREATE_SUCCESS'
export const CLOSE_SUCCESS_MESSAGE = 'CLOSE_SUCCESS_MESSAGE'

export const CLOSE_MODAL = 'CLOSE_MODAL'
export const OPEN_MODAL = 'OPEN_MODAL'
export const OPEN_CONTACT_SUCCESS = 'OPEN_CONTACT_SUCCESS'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const CANCEL_EDIT = 'CANCEL_EDIT'
export const OPEN_CONFIRM_DIALOG = 'OPEN_CONFIRM_DIALOG'
export const CLOSE_CONFIRM_DIALOG = 'CLOSE_CONFIRM_DIALOG'
