export const SUBMIT_CREATE_FORM = 'SUBMIT_CREATE_FORM'

export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const CREATE_SUCCESS = 'CREATE_SUCCESS'
export const CLOSE_SUCCESS_MESSAGE = 'CLOSE_SUCCESS_MESSAGE'

export const OPEN_CONTACT_SUCCESS = 'OPEN_CONTACT_SUCCESS'
